### ISSUE TITLE
Please add support for Typescript

### ISSUE THREAD

**Issue by NickTheFreak97** [kchapelier/fast-2d-poisson-disk-sampling#2]
Hi, I'd love to use this for my project but I'm working with typescript which isn't currently available. Please consider adding support for it in the future. Appreciated

**Comment by kchapelier** [comment]
Hello, you can already use non-typescript modules in your Typescript project:

- with a mixture of `@ts-ignore` and `declare var varname:any` (I'd recommend checking the official doc or some stackoverflow threads for precise up-to-date instructions)
- or with external type declaration file. The Typescript-recommended way to add definitions to non-typescript libraries is to publish them on [@types](https://github.com/DefinitelyTyped/DefinitelyTyped). They have extensive documentation on how to do it. For example, this is how it was handled for [poisson-disk-sampling](https://github.com/kchapelier/poisson-disk-sampling/pull/10).

The project already features precise jsdoc annotation which should be of help in both cases.
